### ISSUE TITLE
可以使用装饰器管理命令，另外配置文件没啥用

### ISSUE THREAD

**Issue by HisAtri** [HTony03/MiniAirways_mod_manager#1]
```
def cmd_register():
    commands = {}

    def register(name):
        def wrapper(func):
            commands[name] = func
            return func
        return wrapper

    def run(name, *args, **kwargs):
        return commands[name](*args, **kwargs)
    return register, run

command, runner = cmd_register()
```

**Comment by HTony03** [comment]
database本身的打算是用作不同版本mod ver的管理，mod介绍与mod前置相关功能所用的
command部分的话…我在想想吧

**Comment by HTony03** [comment]
> database本身的打算是用作不同版本mod ver的管理，mod介绍与mod前置相关功能所用的
> command部分的话…我在想想吧

主要还有一点也就是不确定你游以后的mod发展趋势是什么方向（

**Comment by HisAtri** [comment]
使用配置文件来管理不算个好主意吧，直接启动时遍历目录文件就好了

**Comment by HTony03** [comment]
现在的新想法是 去除database,转到把zip直接放在另一个文件夹：mods内，然后自动解压删除dll（disable/enable部分），直接读取zip的meta-inf，内建database（不外存），如不需要mod则将zip mod拓展名改为.disabled。。。
（也就是遍历目录

**Comment by HisAtri** [comment]
要么用同名的JSON或者yaml写信息，要么想个办法直接从Dotnet dll里面读取插件信息，

总之用压缩包不是什么好主意

**Comment by HTony03** [comment]
同名的话主要是怕用户自己改名啥的会有一些影响（还没啥想法解决）
直接读dll倒是没这问题
（读dll需要的技术力：+++）
（主要是现在他们写dll的话会像mc mod一样这样写上需要的数据吗 不大一定吧）
（而且暂时你游的QQ群发布mod都是zip发布）
（还得看你游mod的发展趋势到底怎样发展才好做进一步判断）

**Comment by HTony03** [comment]
还有一点也就是mc那样是直接.jar而不用解压，直接读取.jar，内置meta-inf.toml读取
你游暂时是需要解压zip的dll到plugins的
（你游也暂时不能读取zip内dll吧，否则啥都不用说了XD

**Comment by HisAtri** [comment]
> 主要是现在他们写dll的话会像mc mod一样这样写上需要的数据吗 不大一定吧

BepInEx 插件都有默认定义插件名、简介这些字段的，具体看开发群里的一些样例就知道。所以理论上来说不需要任何外部手段帮忙记录每个Mod的信息

**Comment by HTony03** [comment]
浅浅尝试了一下，倒是能直接用pythonnet读到modulename了，但是还得慢慢整剩下的
desc和ver啥的等周末试一试（暂时没看到，module东西太多了，没时间试）
（见exampl_dll.py)

**Comment by HTony03** [comment]
V2已删除配置文件相关信息
